In [4]:
#Question1
import numpy as np 
a = np.array([1,3])
b = a.tolist()
print(b)



[1, 3]


In [5]:
#Question2
import numpy as np 
a = np.array([[1,3],[2,4]])
b = a.trace()
print(b)

5


In [13]:
#Question3
import numpy as np 
a = np.array([[1,2],[3,5]])
b = a.ravel()
c = b.tolist()
for i in c: 
    if i > 2:
        print(i,end=" ")

3 5 

In [ ]:
#Question4
import numpy as np 
A = np.array([[4,8],[3,7]])
B = np.array([[1,0],[5,2]])
C = np.array([[4+1,8+0],[3+5,7+2]])

In [21]:
#Question5
import numpy as np 
a = np.random.rand(5,5)
b = a - a.mean(axis = 1, keepdims = True)
print(b)

[[ 0.34258676 -0.60312316 -0.26730402  0.29176988  0.23607053]
 [-0.19848697  0.09359677 -0.23415763  0.11759903  0.2214488 ]
 [-0.27123789  0.51404281 -0.31134052 -0.19779076  0.26632636]
 [ 0.3678774  -0.14626959  0.27819296 -0.15030173 -0.34949903]
 [-0.41355444  0.26617834 -0.15306285  0.24653695  0.053902  ]]
